<a href="https://colab.research.google.com/github/Tai-Suga/AI_ensyu/blob/master/pythonPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
3+4

7

In [2]:
num = 3
moji = "abc"

In [3]:
print(num)
print(moji)

3
abc


In [6]:
num
moji

'abc'

In [7]:
num = 10

In [8]:
num

10

In [11]:
lst = [10,20,30,40,50]
lst[2]

30

In [14]:
lst

[10, 20, 30, 40, 50]

In [12]:
# スライシング
lst[1:4]

[20, 30, 40]

In [15]:
lst[:3]

[10, 20, 30]

In [16]:
lst[3:]

[40, 50]

In [17]:
import numpy as np

In [29]:
# aryを定義する
ary = np.array([1,2,3])
print(ary)

[1 2 3]


In [30]:
print(ary*5)

[ 5 10 15]


In [32]:
ary

array([ 5, 10, 15])

In [33]:
#aryのすべての要素に5をかける
ary=ary*5
print(ary)

[25 50 75]


In [36]:
lst

[10, 20, 30, 40, 50]

In [37]:
lst*5

[10,
 20,
 30,
 40,
 50,
 10,
 20,
 30,
 40,
 50,
 10,
 20,
 30,
 40,
 50,
 10,
 20,
 30,
 40,
 50,
 10,
 20,
 30,
 40,
 50]

In [41]:
# range関数で、0~9までの連続した整数値を生成する
ary = np.array(range(10))
ary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# 平均値
ary.mean()

4.5

In [46]:
# 標準偏差
ary.std()

2.8722813232690143

In [49]:
# 行列の計算
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [50]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [74]:
print(a@b) #行列積を求める

[[19 22]
 [43 50]]


In [54]:
import pandas as pd

In [57]:
# pandas.Series
srs = pd.Series([10,20,30,40,50])
srs

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [60]:
# 添え字
srs[3]

40

In [62]:
# スライシング
srs[1:3]

1    20
2    30
dtype: int64

In [69]:
# インデックス
srs = pd.Series([10,20,30,40,50],index=["one","two","three","four","five"])
srs

one      10
two      20
three    30
four     40
five     50
dtype: int64

In [73]:
# 要約統計量
srs.describe()

count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64

In [ ]:
# dataframeの表示